#################################### common config : ####################################
spring:
  application:
    name: eureka-client
server:
  port: 8081
  servlet:
    context-path: /eureka-client
#eureka注册中心的配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
  instance:
    prefer-ip-address: true
#日志的级别
logging:
  level:
    com.psq.eurekaclient.feign.UserFeign: debug
#feign默认不开启Hystrix，需要配置开启
feign:
  hystrix:
    enabled: true
